//
//  AuthenticationOperation.swift
//  AltStore
//
//  Created by Riley Testut on 6/5/19.
//  Copyright © 2019 Riley Testut. All rights reserved.
//

@preconcurrency import UIKit
import Foundation
import Network
import CoreData
@preconcurrency import AltStoreCore
@preconcurrency import AltSign

private extension UIColor {
    static let altInvertedPrimary = UIColor(named: "SettingsHighlighted")!
}

typealias AuthenticationError = AuthenticationErrorCode.Error
enum AuthenticationErrorCode: Int, ALTErrorEnum, CaseIterable {
    case noTeam
    case noCertificate
    case teamSelectorError
    
    case missingPrivateKey
    case missingCertificate
    
    case certificateLimitReachedFree
    case certificateLimitReachedPaid
    
    var errorFailureReason: String {
        switch self {
        case .noTeam: return NSLocalizedString("Your Apple ID has no developer teams?", comment: "")
        case .noCertificate: return NSLocalizedString("The developer certificate could not be found.", comment: "")
        case .teamSelectorError: return NSLocalizedString("Error presenting team selector view.", comment: "")
        case .missingPrivateKey: return NSLocalizedString("The certificate's private key could not be found.", comment: "")
        case .missingCertificate: return NSLocalizedString("The certificate could not be found.", comment: "")
        case .certificateLimitReachedFree: return NSLocalizedString("You have already exhausted the limit of 1 certificate for free developer accounts. Please revoke the existing certificate and try again.", comment: "")
        case .certificateLimitReachedPaid: return NSLocalizedString("You have already exhausted the maximum certificates that can be generated by a paid developer account. Please revoke at least one certificate and try again.", comment: "")
        }
    }
}

typealias AuthenticationResult = (ALTTeam, ALTCertificate?, ALTAppleAPISession)

private struct SessionCache {
    let team: ALTTeam
    let session: ALTAppleAPISession
}

final class AuthenticationOperation: BaseStandaloneOperation<AuthenticatedOperationContext, AuthenticationResult>, @unchecked Sendable {
    private weak var presentingViewController: UIViewController?
    
    private lazy var navigationController: UINavigationController = {
        let navigationController = self.storyboard.instantiateViewController(withIdentifier: "navigationController") as! UINavigationController
        navigationController.isModalInPresentation = true
        return navigationController
    }()
    
    private lazy var storyboard = UIStoryboard(name: "Authentication", bundle: nil)
    
    private var appleIDEmailAddress: String?
    private var appleIDPassword: String?
    private var shouldShowInstructions = false
    private var activeCertificates: [ALTCertificate] = []
    
    private let operationQueue = OperationQueue()
    
    private var submitCodeAction: UIAlertAction?
    
    let skipDeviceRegistration: Bool
    let skipCertificateProvisioning: Bool

    init(context: AuthenticatedOperationContext, presentingViewController: UIViewController?, skipDeviceRegistration: Bool = false, skipCertificateProvisioning: Bool = false) throws {
        self.presentingViewController = presentingViewController
        self.skipDeviceRegistration = skipDeviceRegistration
        self.skipCertificateProvisioning = skipCertificateProvisioning
        
        try super.init(context: context)
        
        self.operationQueue.name = "com.altstore.AuthenticationOperation"
    }
    
    override func execute(parentProgress: Progress?) async throws -> AuthenticationResult {
        debugLog("[AuthenticationOperation] execute() started")
        defer { debugLog("[AuthenticationOperation] execute() completed") }
        try await super.executePreconditionCheck(parentProgress: parentProgress)

        // Reset Keychain if email address changed
        if let newEmail = self.appleIDEmailAddress,
           let currentEmail = AuthManager.shared.currentAppleID,
           newEmail.lowercased() != currentEmail.lowercased() {
            self.verboseLog("[Authentication] Email address changed. Clearing cached session.")
            AuthManager.shared.clearSession()
        }

        // PHASE 1: Resolve valid session (Coalesced)
        let authResult = try await TaskChainCoalescer.shared.coalesce(key: "apple_auth") { () -> AuthenticationResult in
            // Check L1 - Session Cache
            if let session = AuthManager.shared.session, 
               let team = AuthManager.shared.team 
            {
                let cache = SessionCache(team: team, session: session)
                if let validatedResult = try await self.validateSessionCache(cache) {
                    return validatedResult
                }
            }
            
            // L2: Sign-in (Silent credentials sign-in or fallback to UI)
            return try await self.performNewSignIn()
        }
        
        self.context.team = authResult.0
        self.context.signingCertificate = authResult.1
        self.context.session = authResult.2

        // PHASE 2: Post-Authentication Work (Unlocked)
        return try await self.performPostAuthenticationWork(result: authResult)
    }
    
    private func validateSessionCache(_ cache: SessionCache) async throws -> AuthenticationResult? {
        // Update anisette data if expired and provisioning is required
        if !self.skipCertificateProvisioning && cache.session.anisetteData.date.timeIntervalSinceNow < -40.0 {
            do {
                let anisetteData = try await FetchAnisetteDataOperation(context: self.context).execute(parentProgress: self.progress)
                cache.session.anisetteData = anisetteData
            } catch {
                self.verboseLog("[Authentication] Failed to update anisette data for cached session: \(error)")
            }
        }
        
        do {
            let certificates = try await ALTAppleAPI.shared.fetchCertificates(for: cache.team, session: cache.session)
            self.activeCertificates = certificates
            self.context.activeCertificates = certificates
            
            var certToUse: ALTCertificate?
            if let keychainCert = CertificateManager.shared.activeCertificate,
               certificates.contains(where: { $0.serialNumber == keychainCert.serialNumber })
            {
                certToUse = keychainCert.certificate
            }
            
            if self.skipCertificateProvisioning || (certToUse != nil && certificates.contains(where: { $0.serialNumber == certToUse?.serialNumber })) {
                self.debugLog("[Authentication] SessionCache is valid. (using certificate: \(certToUse?.serialNumber ?? "nil"))")
                self.context.team = cache.team
                self.context.session = cache.session
                self.context.signingCertificate = certToUse
                return (cache.team, certToUse, cache.session)
            } else {
                self.debugLog("[Authentication] Cached/active certificate is no longer active on developer portal.")
            }
        } catch {
            self.debugLog("[Authentication] Failed to validate SessionCache: \(error)")
        }
        return nil
    }
    
    private func performNewSignIn() async throws -> AuthenticationResult {
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        
        self.verboseLog("[Authentication] execute: Invoking signIn...")
        let (account, session) = try await self.signIn()
        self.debugLog("[Authentication] execute: signIn completed successfully.")
        self.context.session = session
        self.setProgress(stepWeight)
        if self.isCancelled { throw OperationError.cancelled }
        
        self.verboseLog("[Authentication] execute: Invoking fetchTeam...")
        let team = try await self.fetchTeam(for: account, session: session)
        self.debugLog("[Authentication] execute: fetchTeam completed successfully.")
        self.context.team = team
        
        self.debugLog("[Authentication] Saving team & account immediately after fetchTeam")
        AuthManager.shared.team = team
        AuthManager.shared.session = session
        try await self.save(team)
        
        let certificate: ALTCertificate?
        
        // Check if a custom/third-party certificate is active
        var isCustomCertActive = false
        if let activeCert = CertificateManager.shared.activeCertificate?.certificate,
           let data = activeCert.data {
            let details = SideStore.parseCertificate(derData: data)
            let belongsToAuthenticatedTeam = details.subject.contains(team.identifier) || details.issuer.contains(team.identifier)
            if !belongsToAuthenticatedTeam {
                self.debugLog("[Authentication] Custom/third-party active certificate detected (Subject OU does not match Team ID '\(team.identifier)').")
                isCustomCertActive = true
            }
        }
        
        if self.skipCertificateProvisioning || isCustomCertActive {
            if isCustomCertActive {
                self.debugLog("[Authentication] Using custom active certificate '\(CertificateManager.shared.activeCertificate?.certificate.serialNumber ?? "nil")' for signing. Bypassing portal fetch.")
            } else {
                self.verboseLog("[Authentication] execute: Skipping certificate provisioning.")
            }
            certificate = CertificateManager.shared.activeCertificate?.certificate
            self.context.signingCertificate = certificate
        } else {
            self.verboseLog("[Authentication] execute: Invoking fetchCertificate...")
            certificate = try await self.fetchCertificate(for: team, session: session)
            self.debugLog("[Authentication] execute: fetchCertificate completed successfully. Serial: \(certificate?.serialNumber ?? "nil")")
            self.context.signingCertificate = certificate
        }
        
        // Only update the global active certificate if the user doesn't have a custom third-party certificate selected
        var shouldUpdateActiveCertificate = true
        if isCustomCertActive {
            self.debugLog("[Authentication] Custom/third-party certificate is active. Skipping active certificate overwrite.")
            shouldUpdateActiveCertificate = false
        }
        
        if shouldUpdateActiveCertificate {
            self.debugLog("[Authentication] Saving certificate after fetching certificate")
            try? CertificateManager.shared.setActiveCertificate(certificate)
        }
        
        return (team, certificate, session)
    }
    
    private func performPostAuthenticationWork(result: AuthenticationResult) async throws -> AuthenticationResult {
        let (team, certificate, session) = result
        let stepWeight: Int64 = self.skipDeviceRegistration ? 33 : 25
        
        do {
            self.debugLog("[Authentication] execute: Invoking save(team) checkpoint...")
            try await self.save(team)
            self.setProgress(stepWeight * 2)
            if self.isCancelled { throw OperationError.cancelled }
            
            self.setProgress(stepWeight * 3)
            if self.isCancelled { throw OperationError.cancelled }
            
            if !self.skipDeviceRegistration {
                self.verboseLog("[Authentication] execute: Invoking registerCurrentDevice...")
                _ = try await self.registerCurrentDevice(for: team, session: session)
                self.debugLog("[Authentication] execute: registerCurrentDevice completed successfully.")
                self.setProgress(stepWeight * 4)
                if self.isCancelled { throw OperationError.cancelled }
            }
            
            self.setProgress(100)
            self.verboseLog("[Authentication] execute: Invoking save(team)...")
            try await self.save(team)
            self.debugLog("[Authentication] execute: save(team) completed successfully.")
            if self.isCancelled { throw OperationError.cancelled }
            
            self.verboseLog("[Authentication] execute: Invoking cacheAppIDs...")
            try await self.cacheAppIDs(team: team, session: session)
            self.debugLog("[Authentication] execute: cacheAppIDs completed successfully.")
            
            self.verboseLog("[Authentication] execute: Invoking postAuthenticationCleanup with success...")
            try await self.postAuthenticationCleanup(result: .success((team, certificate, session)))
            self.debugLog("[Authentication] execute: postAuthenticationCleanup completed successfully.")
            return (team, certificate, session)
        } catch {
            self.debugLog("[Authentication] execute: Caught error in post-auth flow: \(error). Cleaning up...")
            try? await self.postAuthenticationCleanup(result: .failure(error))
            throw error
        }
    }
    
    private func save(_ altTeam: ALTTeam) async throws {
        guard let context = self.context.dbBackgroundContext else {
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        try await context.perform {
            try self.saveTeamAndAccount(altTeam, in: context)
        }
    }
    
    private func saveTeamAndAccount(_ altTeam: ALTTeam, in context: NSManagedObjectContext) throws {
        let account: Account
        let team: Team
        
        if let tempAccount = Account.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Account.identifier), altTeam.account.identifier), in: context) {
            account = tempAccount
        } else {
            account = Account(altTeam.account, context: context)
        }
        
        if let tempTeam = Team.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Team.identifier), altTeam.identifier), in: context) {
            team = tempTeam
        } else {
            team = Team(altTeam, account: account, context: context)
        }
        
        account.update(account: altTeam.account)
        
        if let providedEmailAddress = self.appleIDEmailAddress {
            // Save the user's provided email address instead of the one associated with their account (which may be outdated).
            account.appleID = providedEmailAddress
        }
        
        team.update(team: altTeam)
        
        try context.save()
    }
    
    private func postAuthenticationCleanup(result: Result<(ALTTeam, ALTCertificate?, ALTAppleAPISession), Error>) async throws {
        self.verboseLog("[Authentication] postAuthenticationCleanup: Starting cleanup...")
        switch result {
        case .failure(let error):
            self.debugLog("[Authentication] postAuthenticationCleanup: Failure result - \(error.localizedDescription)")
            self.verboseLog("[AuthenticationOperation] Failed to authenticate account. \(error.localizedDescription)")
            
            self.verboseLog("[Authentication] postAuthenticationCleanup: Dismissing navigation controller on main actor (failure case)...")
            await MainActor.run {
                self.navigationController.dismiss(animated: true) {
                    self.debugLog("[Authentication] postAuthenticationCleanup: Navigation controller dismissed (failure case).")
                }
            }
            return
            
        case .success((let team, _, _)):
            self.verboseLog("[Authentication] postAuthenticationCleanup: Authentication Success for team \(team.identifier) account.")
        }
        
        guard let context = self.context.dbBackgroundContext else {
            self.debugLog("[Authentication] postAuthenticationCleanup: Error - context.dbBackgroundContext is nil!")
            throw OperationError.invalidParameters("AuthenticationOperation: context.dbBackgroundContext is nil")
        }
        
        self.verboseLog("[Authentication] postAuthenticationCleanup: Performing database updates inside context...")
        do {
            try await context.perform {
                try self.postAuthenticationCleanup(result: result, in: context)
            }
        } catch {
            self.debugLog("[Authentication] postAuthenticationCleanup: error occured when performing cleanup: \(error)")
        }
        self.verboseLog("[Authentication] postAuthenticationCleanup: Database updates completed.")
        
        do {
            let (altTeam, altCertificate, session) = try result.get()
            if let altCertificate = altCertificate, !self.skipCertificateProvisioning {
                self.verboseLog("[Authentication] postAuthenticationCleanup: Checking instructions and resign alerts...")
                let didShowInstructions = await self.showInstructionsIfNecessary()
                self.verboseLog("[Authentication] postAuthenticationCleanup: didShowInstructions = \(didShowInstructions)")
                
                let signer = ALTSigner(team: altTeam, certificate: altCertificate)
                // Resign screen must go last since a successful resign/reinstall will cause the app to quit.
                let didShowResignAlert = await self.showResignScreenIfNecessary(signer: signer, session: session)
                self.verboseLog("[Authentication] postAuthenticationCleanup: didShowResignAlert = \(didShowResignAlert)")
                if !didShowResignAlert {
                    try? CertificateManager.shared.setActiveCertificate(altCertificate)
                    self.verboseLog("[Authentication] postAuthenticationCleanup: Cached signing certificate in Keychain.")
                }
            }
        } catch {
            self.debugLog("[Authentication] postAuthenticationCleanup: Skipping post-auth actions because result was failure/error: \(error)")
            self.verboseLog("[AuthenticationOperation] Skipping post-authentication alerts and certificate caching because authentication failed: \(error.localizedDescription)")
        }
        
        self.verboseLog("[Authentication] postAuthenticationCleanup: Dismissing navigation controller on main actor...")
        await MainActor.run {
            self.navigationController.dismiss(animated: true) {
                self.debugLog("[Authentication] postAuthenticationCleanup: Navigation controller dismissed.")
            }
        }
    }
    
    private func postAuthenticationCleanup(result: Result<(ALTTeam, ALTCertificate?, ALTAppleAPISession), Error>, in context: NSManagedObjectContext) throws {
        let (altTeam, _, _) = try result.get()
        
        guard
            let account = Account.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Account.identifier), altTeam.account.identifier), in: context),
            let team = Team.first(satisfying: NSPredicate(format: "%K == %@", #keyPath(Team.identifier), altTeam.identifier), in: context)
        else { throw AuthenticationError(.noTeam) }
        // Account
        account.isActiveAccount = true
        
        let otherAccountsFetchRequest = Account.fetchRequest() as NSFetchRequest<Account>
        otherAccountsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Account.identifier), account.identifier)
        
        let otherAccounts = try context.fetch(otherAccountsFetchRequest)
        for account in otherAccounts {
            account.isActiveAccount = false
        }
        
        // Team
        team.isActiveTeam = true
        
        let otherTeamsFetchRequest = Team.fetchRequest() as NSFetchRequest<Team>
        otherTeamsFetchRequest.predicate = NSPredicate(format: "%K != %@", #keyPath(Team.identifier), team.identifier)
        
        let otherTeams = try context.fetch(otherTeamsFetchRequest)
        for team in otherTeams {
            team.isActiveTeam = false
        }

        let isSparseRestorePatched   = ProcessInfo().sparseRestorePatched
        let isAppLimitDisabled       = UserDefaults.standard.isAppLimitDisabled

        UserDefaults.standard.activeAppsLimit = nil
        // TODO: @mahee96: is the minimum ver match for ios 13.3.1 check required?
        //                 if so what is the app limit? As nil app limit specifies unlimited apps?!
        if team.type == .free {
            if (!isAppLimitDisabled && isSparseRestorePatched) ||
                (isAppLimitDisabled && !isSparseRestorePatched) {
                    UserDefaults.standard.activeAppsLimit = InstalledApp.freeAccountActiveAppsLimit
            }
        }
        
        // Update keychain via AuthManager
        AuthManager.shared.currentAppleID = self.appleIDEmailAddress ?? altTeam.account.appleID // Prefer the user's provided email address over the one associated with their account (which may be outdated).
        if let appleIDPassword = self.appleIDPassword {
            AuthManager.shared.password = appleIDPassword
        }
        
        try context.save()
    }
    
    @MainActor
    private func present(_ viewController: UIViewController) -> Bool {
        guard let presentingViewController = self.presentingViewController else { return false }
        
        self.navigationController.view.tintColor = .altInvertedPrimary
        
        if self.navigationController.viewControllers.isEmpty {
            guard presentingViewController.presentedViewController == nil else { return false }
            
            self.navigationController.setViewControllers([viewController], animated: false)            
            presentingViewController.present(self.navigationController, animated: true, completion: nil)
        } else {
            viewController.navigationItem.leftBarButtonItem = nil
            self.navigationController.pushViewController(viewController, animated: true)
        }
        
        return true
    }

    @MainActor
    private func presentAlert(_ alert: UIAlertController) -> Bool {
        if self.navigationController.presentingViewController != nil {
            self.navigationController.present(alert, animated: true, completion: nil)
            return true
        } else if let presentingViewController = self.presentingViewController {
            presentingViewController.present(alert, animated: true, completion: nil)
            return true
        } else if let topViewController = UIApplication.shared.connectedScenes
            .filter({ $0.activationState == .foregroundActive })
            .compactMap({ $0 as? UIWindowScene })
            .first?.windows
            .first(where: { $0.isKeyWindow })?
            .rootViewController {
            var top = topViewController
            while let presented = top.presentedViewController {
                top = presented
            }
            top.present(alert, animated: true, completion: nil)
            return true
        } else {
            self.debugLog("[Authentication] Could not find any view controller to present alert.")
            return false
        }
    }
    
    private func signIn() async throws -> (ALTAccount, ALTAppleAPISession) {
        if let adsid = AuthManager.shared.adsid, let xcodeToken = AuthManager.shared.xcodeToken {
            self.verboseLog("[AuthenticationOperation] Authenticating Apple ID with tokens...")
            do {
                let (account, session) = try await self.authenticateWithToken(adsid: adsid, xcodeToken: xcodeToken)
                return (account, session)
            } catch {
                self.debugLog("[AuthenticationOperation] Authentication failed with token. Fall back to email and password login: \(error)")
            }
        }
        
        if let appleID = AuthManager.shared.currentAppleID, let password = AuthManager.shared.password {
            self.debugLog("Authenticating Apple ID...")
            
            do {
                let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                self.appleIDPassword = password
                return (account, session)
            } catch ALTAppleAPIError.incorrectCredentials, ALTAppleAPIError.appSpecificPasswordRequired {
                return try await self.presentSignInUI()
            } catch {
                throw error
            }
        } else {
            return try await self.presentSignInUI()
        }
    }
    
    @MainActor
    private func presentSignInUI() async throws -> (ALTAccount, ALTAppleAPISession) {
        self.verboseLog("[Authentication] presentSignInUI: Preparing to present sign-in UI...")
        return try await withCheckedThrowingContinuation { continuation in
            var activeContinuation: CheckedContinuation<(ALTAccount, ALTAppleAPISession), Error>? = continuation
            let authenticationViewController = self.storyboard.instantiateViewController(withIdentifier: "authenticationViewController") as! AuthenticationViewController
            authenticationViewController.authenticationHandler = { (appleID, password, completionHandler) in
                self.verboseLog("[Authentication] presentSignInUI: authenticationHandler invoked for Apple ID \(appleID)...")
                Task {
                    do {
                        let (account, session) = try await self.authenticate(appleID: appleID, password: password)
                        self.debugLog("[Authentication] presentSignInUI: AuthenticationOperation.authenticate succeeded.")
                        completionHandler(.success((account, session)))
                    } catch {
                        self.debugLog("[Authentication] presentSignInUI: AuthenticationOperation.authenticate failed: \(error)")
                        completionHandler(.failure(error))
                    }
                }
            }
            authenticationViewController.completionHandler = { (result) in
                guard let continuationToResume = activeContinuation else {
                    self.debugLog("[Authentication] presentSignInUI: completionHandler invoked but activeContinuation is NIL (already consumed).")
                    return
                }
                activeContinuation = nil
                
                if result == nil && authenticationViewController.presentingViewController != nil {
                    authenticationViewController.dismiss(animated: true)
                }
                
                self.debugLog("[Authentication] presentSignInUI: completionHandler invoked (result is \(result != nil ? "success" : "nil/cancelled"))")
                if let (account, session, password) = result {
                    // We presented the Auth UI and the user signed in.
                    // In this case, we'll assume we should show the instructions again.
                    self.shouldShowInstructions = true
                    
                    self.appleIDPassword = password
                    self.verboseLog("[Authentication] presentSignInUI: Resuming continuation with account: \(account.appleID)")
                    continuationToResume.resume(returning: (account, session))
                } else {
                    self.debugLog("[Authentication] presentSignInUI: Resuming continuation with cancelled error.")
                    continuationToResume.resume(throwing: OperationError.cancelled)
                }
            }
            
            self.verboseLog("[Authentication] presentSignInUI: Presenting authenticationViewController...")
            if !self.present(authenticationViewController) {
                guard let continuationToResume = activeContinuation else {
                    self.debugLog("[Authentication] presentSignInUI: Failed to present, but activeContinuation is NIL (already consumed).")
                    return
                }
                activeContinuation = nil
                self.debugLog("[Authentication] presentSignInUI: Failed to present authenticationViewController!")
                continuationToResume.resume(throwing: OperationError.notAuthenticated)
            } else {
                self.verboseLog("[Authentication] presentSignInUI: Presented successfully.")
            }
        }
    }
    
    private func authenticateWithToken(adsid: String, xcodeToken: String) async throws -> (ALTAccount, ALTAppleAPISession) {
        let anisetteData = try await FetchAnisetteDataOperation(context: self.context)
            .execute(parentProgress: progress)
        
        let session = ALTAppleAPISession(dsid: adsid, authToken: xcodeToken, anisetteData: anisetteData)
        let account = try await ALTAppleAPI.shared.fetchAccount2(session: session)
        
        return (account, session)
    }
    
    private func authenticate(appleID: String, password: String) async throws -> (ALTAccount, ALTAppleAPISession) {
        self.appleIDEmailAddress = appleID
        
        let anisetteData = try await FetchAnisetteDataOperation(context: self.context)
            .execute(parentProgress: progress)
        
        let verificationHandler: ((@escaping (String?) -> Void) -> Void)?
        
        if let presentingViewController = self.presentingViewController {
            verificationHandler = { (completionHandler) in
                Task { @MainActor in
                    let alertController = UIAlertController(title: NSLocalizedString("Please enter the 6-digit verification code that was sent to your Apple devices.", comment: ""), message: nil, preferredStyle: .alert)
                    var observer: NSObjectProtocol?
                    alertController.addTextField { (textField) in
                        textField.autocorrectionType = .no
                        textField.autocapitalizationType = .none
                        textField.keyboardType = .numberPad
                        
                        observer = NotificationCenter.default.addObserver(forName: UITextField.textDidChangeNotification, object: textField, queue: .main) { [weak self] (notification) in
                            guard let self = self, let textField = notification.object as? UITextField else { return }
                            self.submitCodeAction?.isEnabled = (textField.text ?? "").count == 6
                        }
                    }
                    
                    let submitAction = UIAlertAction(title: NSLocalizedString("Continue", comment: ""), style: .default) { (action) in
                        if let observer = observer {
                            NotificationCenter.default.removeObserver(observer)
                        }
                        let textField = alertController.textFields?.first
                        
                        let code = textField?.text ?? ""
                        completionHandler(code)
                    }
                    submitAction.isEnabled = false
                    alertController.addAction(submitAction)
                    self.submitCodeAction = submitAction
                    
                    alertController.addAction(UIAlertAction(title: RSTSystemLocalizedString("Cancel"), style: .cancel) { (action) in
                        if let observer = observer {
                            NotificationCenter.default.removeObserver(observer)
                        }
                        completionHandler(nil)
                    })
                    
                    if self.navigationController.presentingViewController != nil {
                        self.navigationController.present(alertController, animated: true, completion: nil)
                    } else {
                        presentingViewController.present(alertController, animated: true, completion: nil)
                    }
                }
            }
        } else {
            verificationHandler = nil
        }
        
        let (account, session) = try await ALTAppleAPI.shared.authenticate(
            appleID: appleID,
            password: password,
            anisetteData: anisetteData,
            verificationHandler: verificationHandler
        )
        
        AuthManager.shared.adsid = session.dsid
        AuthManager.shared.xcodeToken = session.authToken
        
        return (account, session)
    }
    
    private func fetchTeam(for account: ALTAccount, session: ALTAppleAPISession) async throws -> ALTTeam {
        let teams = try await ALTAppleAPI.shared.fetchTeams(for: account, session: session)
        
        let activeTeamFromDB = await DatabaseManager.shared.persistentContainer.performBackgroundTask { context in
            DatabaseManager.shared.activeTeam(in: context)
        }
        
        if let activeTeam = activeTeamFromDB, let altTeam = teams.first(where: { $0.identifier == activeTeam.identifier }) {
            return altTeam
        }
        
        return try await self.selectTeam(from: teams)
    }
    
    @MainActor
    private func selectTeam(from teams: [ALTTeam]) async throws -> ALTTeam {
        if teams.count <= 1 {
            if let team = teams.first {
                return team
            } else {
                throw AuthenticationError(.noTeam)
            }
        }
        
        return try await withCheckedThrowingContinuation { continuation in
            let selectTeamViewController = self.storyboard.instantiateViewController(withIdentifier: "selectTeamViewController") as! SelectTeamViewController

            selectTeamViewController.teams = teams
            selectTeamViewController.completionHandler = { result in
                continuation.resume(with: result)
            }

            let presented = self.present(selectTeamViewController)
            if !presented {
                continuation.resume(throwing: AuthenticationError(.noTeam))
            }
        }
    }
    
    private func fetchCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let certificates = try await ALTAppleAPI.shared.fetchCertificates(for: team, session: session)
        self.activeCertificates = certificates
        self.context.activeCertificates = certificates
        
        let bundleCertID = Bundle.main.object(forInfoDictionaryKey: Bundle.Info.certificateID) as? String
        
        let binaryCert = CertificateManager.shared.getSigningCertificate(at: Bundle.main.bundleURL)
        
        if let activeCert = CertificateManager.shared.activeCertificate,
           let certificate = certificates.first(where: { $0.serialNumber == activeCert.serialNumber })
        {
            activeCert.certificate.machineIdentifier = certificate.machineIdentifier
            if let bundleCertID = bundleCertID, bundleCertID.lowercased() != activeCert.serialNumber.lowercased() {
                self.debugLog("[Authentication] Active certificate (\(activeCert.serialNumber)) and running bundle certificate (\(bundleCertID)) mismatch detected. Running Bundle Certificate is still active on the Paid account portal. Using active Keychain certificate.")
            }
            return activeCert.certificate
        }
        
        if let binaryCert = binaryCert,
           let localCert = CertificateManager.shared.getLocalCertificate(serialNumber: binaryCert.serialNumber),
           let certificate = certificates.first(where: { $0.serialNumber == binaryCert.serialNumber }) {
            localCert.machineIdentifier = certificate.machineIdentifier
            self.debugLog("[Authentication] Using running bundle certificate (\(binaryCert.serialNumber)) found in binary and active on portal.")
            return localCert
        }
        
        if certificates.isEmpty {
            // No certificates, so request a new one.
            return try await self.requestCertificate(for: team, session: session)
        } else {
            // We don't have private keys for any of the certificates,
            // so we need to revoke one and create a new one.
            return try await self.replaceCertificate(ourCertificates: certificates, for: team, session: session)
        }
    }
    
    private func requestCertificate(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let deviceName = await UIDevice.current.name
        let machineName: String = "SideStore - \(team.account.firstName)'s \(deviceName)"
        self.debugLog("[Authentication] requestCertificate: Starting request...")
        self.verboseLog("[Authentication] requestCertificate: Starting request for machineName '\(machineName)'...")
        do {
            self.verboseLog("[Authentication] requestCertificate: Calling ALTAppleAPI.shared.addCertificate...")
            let certificate = try await ALTAppleAPI.shared.addCertificate(machineName: machineName, to: team, session: session)
            self.verboseLog("[Authentication] requestCertificate: addCertificate succeeded. Serial: \(certificate.serialNumber ?? "nil")")
            guard let privateKey = certificate.privateKey else {
                self.debugLog("[Authentication] requestCertificate: Error - missing private key!")
                throw AuthenticationError(.missingPrivateKey)
            }
            self.verboseLog("[Authentication] requestCertificate: Fetching certificates to match...")
            let certificates = try await ALTAppleAPI.shared.fetchCertificates(for: team, session: session)
            self.verboseLog("[Authentication] requestCertificate: fetchCertificates returned \(certificates.count) certificates.")
            guard let matchedCertificate = certificates.first(where: { $0.serialNumber == certificate.serialNumber }) else {
                self.debugLog("[Authentication] requestCertificate: Error - missing matched certificate!")
                throw AuthenticationError(.missingCertificate)
            }
            
            matchedCertificate.privateKey = privateKey
            self.verboseLog("[Authentication] requestCertificate: Successfully retrieved matched certificate with private key.")
            return matchedCertificate
        } catch {
            self.debugLog("[Authentication] requestCertificate: Failed with error: \(error)")
            let underlying = error as NSError
            if underlying.domain == ALTAppleAPIErrorDomain && underlying.code == ALTAppleAPIError.tooManyCertificates.rawValue {
                let friendlyError: AuthenticationError
                if team.type == .free {
                    friendlyError = AuthenticationError(.certificateLimitReachedFree)
                } else {
                    friendlyError = AuthenticationError(.certificateLimitReachedPaid)
                }
                let wrappedError = NSError(
                    domain: (friendlyError as NSError).domain,
                    code: (friendlyError as NSError).code,
                    userInfo: [
                        NSLocalizedDescriptionKey: friendlyError.localizedDescription,
                        NSLocalizedFailureReasonErrorKey: friendlyError.failureReason ?? "",
                        NSUnderlyingErrorKey: underlying
                    ]
                )
                throw wrappedError
            } else {
                throw error
            }
        }
    }
    
    @MainActor
    private func replaceCertificate(ourCertificates: [ALTCertificate], for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        let filteredCertificates = ourCertificates.filter { a in
            a.machineName?.starts(with: "SideStore") == true || a.machineName?.starts(with: "AltStore") == true
        }
        self.debugLog("[Authentication] replaceCertificate: Starting. Total certs: \(ourCertificates.count), filtered: \(filteredCertificates.count)")
        
        if filteredCertificates.isEmpty {
            self.verboseLog("[Authentication] replaceCertificate: No filtered certificates. Requesting new...")
            return try await self.requestCertificate(for: team, session: session)
        }
        
        // We don't have private keys for any of the certificates,
        // so we need to revoke one and create a new one.
        var certsText = ""
        for certificate in filteredCertificates {
            if let name = certificate.machineName {
                certsText.append("\(name)\n")
            }
        }
        
        self.debugLog("[Authentication] replaceCertificate: Presenting revoke alert...")
        let action = try await self.showRevokeAlert(certsText: certsText, teamType: team.type)
        self.debugLog("[Authentication] replaceCertificate: User action was \(action)")
        switch action {
        case .keepExisting:
            self.verboseLog("[Authentication] replaceCertificate: Keeping existing, calling requestCertificate...")
            return try await self.requestCertificate(for: team, session: session)
            
        case .revokeAll:
            self.debugLog("[Authentication] replaceCertificate: Revoking all filtered certificates...")
            var firstError: Error? = nil
            for certificate in filteredCertificates {
                do {
                    self.verboseLog("[Authentication] replaceCertificate: Revoking certificate '\(certificate.machineName ?? "nil")' (Serial: \(certificate.serialNumber ?? "nil"))...")
                    try await ALTAppleAPI.shared.revoke(certificate, for: team, session: session)
                    self.verboseLog("[Authentication] replaceCertificate: Revoke succeeded.")
                } catch {
                    self.debugLog("[Authentication] replaceCertificate: Revoke failed with error: \(error)")
                    if firstError == nil {
                        firstError = error
                    }
                }
            }
            if let error = firstError {
                self.debugLog("[Authentication] replaceCertificate: Error occurred during revocation, throwing...")
                throw error
            } else {
                self.debugLog("[Authentication] replaceCertificate: All certificates successfully revoked. Requesting new certificate...")
                return try await self.requestCertificate(for: team, session: session)
            }
        }
    }

    enum RevokeAlertAction {
        case revokeAll
        case keepExisting
    }

    @MainActor
    private func showRevokeAlert(certsText: String, teamType: ALTTeamType) async throws -> RevokeAlertAction {
        self.verboseLog("[Authentication] showRevokeAlert: Preparing to show revoke alert...")
        return try await withCheckedThrowingContinuation { continuation in
            let alertController = UIAlertController(title: NSLocalizedString("Would you like to revoke your previous certificates?\n\(certsText)", comment: ""), message: nil, preferredStyle: .alert)
            
            let noAction = UIAlertAction(title: NSLocalizedString("No", comment: ""), style: .default) { _ in
                self.debugLog("[Authentication] showRevokeAlert: User clicked No.")
                alertController.dismiss(animated: true) {
                    if teamType == .free {
                        let warningAlert = UIAlertController(
                            title: NSLocalizedString("Warning", comment: ""),
                            message: NSLocalizedString("SideStore cannot manage the existing certificate without owning its private key. The apps signed with the existing certificate will expire soon unless they are resigned and renewed explicitly by SideStore.", comment: ""),
                            preferredStyle: .alert
                        )
                        warningAlert.addAction(UIAlertAction(title: NSLocalizedString("OK", comment: ""), style: .default) { _ in
                            self.verboseLog("[Authentication] showRevokeAlert: User acknowledged warning OK.")
                            warningAlert.dismiss(animated: true) {
                                continuation.resume(returning: .keepExisting)
                            }
                        })
                        
                        let presented = self.presentAlert(warningAlert)
                        if !presented {
                            self.debugLog("[Authentication] showRevokeAlert: Warning alert could not be presented, resuming with keepExisting.")
                            continuation.resume(returning: .keepExisting)
                        }
                    } else {
                        continuation.resume(returning: .keepExisting)
                    }
                }
            }
            
            let yesAction = UIAlertAction(title: NSLocalizedString("Yes", comment: ""), style: .default) { _ in
                self.debugLog("[Authentication] showRevokeAlert: User clicked Yes.")
                alertController.dismiss(animated: true) {
                    continuation.resume(returning: .revokeAll)
                }
            }
            
            alertController.addAction(noAction)
            alertController.addAction(yesAction)
            
            self.verboseLog("[Authentication] showRevokeAlert: Presenting alert...")
            let presented = self.presentAlert(alertController)
            if !presented {
                self.debugLog("[Authentication] showRevokeAlert: Alert could not be presented, resuming with keepExisting.")
                continuation.resume(returning: .keepExisting)
            }
        }
    }
    
    private func registerCurrentDevice(for team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTDevice {
        guard let udid = try await fetchUDID() else {
            throw OperationError.unknownUDID
        }
        
        let devices = try await ALTAppleAPI.shared.fetchDevices(for: team, types: [.iphone, .ipad], session: session)
        if let device = devices.first(where: { $0.identifier == udid }) {
            return device
        } else {
            return try await ALTAppleAPI.shared.registerDevice(name: UIDevice.current.name, identifier: udid, type: .iphone, team: team, session: session)
        }
    }
    
    private func cacheAppIDs(team: ALTTeam, session: ALTAppleAPISession) async throws {
        let syncAppIDsOperation = try SyncAppIDsOperation(context: self.context)
        try await syncAppIDsOperation.execute(parentProgress: progress)
    }
    
    @MainActor
    private func showInstructionsIfNecessary() async -> Bool {
        self.verboseLog("[Authentication] showInstructionsIfNecessary: entering method, shouldShowInstructions = \(self.shouldShowInstructions)")
        guard self.shouldShowInstructions else {
            self.verboseLog("[Authentication] showInstructionsIfNecessary: shouldShowInstructions is false, returning false")
            return false
        }
        
        return await withCheckedContinuation { continuation in
            self.verboseLog("[Authentication] showInstructionsIfNecessary: instantiating instructionsViewController...")
            let instructionsViewController = self.storyboard.instantiateViewController(withIdentifier: "instructionsViewController") as! InstructionsViewController
            instructionsViewController.showsBottomButton = true
            instructionsViewController.completionHandler = {
                self.verboseLog("[Authentication] showInstructionsIfNecessary: instructionsViewController completionHandler invoked")
                continuation.resume(returning: true)
            }
            
            self.verboseLog("[Authentication] showInstructionsIfNecessary: presenting instructionsViewController...")
            let presented = self.present(instructionsViewController)
            self.verboseLog("[Authentication] showInstructionsIfNecessary: present returned \(presented)")
            if !presented {
                self.debugLog("[Authentication] showInstructionsIfNecessary: present failed, resuming continuation with false")
                continuation.resume(returning: false)
            }
        }
    }
    
    @MainActor
    private func showResignScreenIfNecessary(signer: ALTSigner, session: ALTAppleAPISession) async -> Bool {
        self.verboseLog("[Authentication] showResignScreenIfNecessary: entering method")
        guard let appBundle = ALTApplication(fileURL: Bundle.main.bundleURL), let provisioningProfile = appBundle.provisioningProfile else {
            self.verboseLog("[Authentication] showResignScreenIfNecessary: Application bundle or provisioning profile nil, returning false")
            return false
        }
        
        let result = CodeSignValidator.validate(
            runningProfile: provisioningProfile,
            activeCertificates: self.activeCertificates,
            signerCertificate: signer.certificate,
            signerTeam: signer.team
        )
        
        switch result {
        case .success:
            self.verboseLog("[Authentication] showResignScreenIfNecessary: Validation succeeded, no resign required.")
            return false
            
        case .failure(let reason):
            self.debugLog("[Authentication] Signing certificate mismatch detected: \(reason)")
            
            // For Paid Developer accounts, if the certificate used to sign the current installation
            // is still active on Apple's portal (which shows as .privateKeyLost or .externalSigner),
            // we don't need to warn the user or force a resign.
            if signer.team.type != .free && (reason == .privateKeyLost || reason == .externalSigner) {
                self.debugLog("[Authentication] Running certificate is still active on the Paid account portal. Skipping resign screen.")
                return false
            }
            
            return await withCheckedContinuation { continuation in
                self.verboseLog("[Authentication] showResignScreenIfNecessary: instantiating resignAltStoreViewController...")
                let context = AuthenticatedOperationContext(context: self.context)
                
                let resignViewController = self.storyboard.instantiateViewController(withIdentifier: "resignAltStoreViewController") as! ResignAltStoreViewController
                resignViewController.context = context
                resignViewController.mismatchReason = reason
                resignViewController.completionHandler = { [weak self] result in
                    switch result {
                    case .success:
                        self?.verboseLog("[Authentication] showResignScreenIfNecessary: resignViewController completionHandler success")
                        continuation.resume(returning: true)
                    case .failure:
                        self?.verboseLog("[Authentication] showResignScreenIfNecessary: resignViewController completionHandler failure/cancelled")
                        self?.context.isSideStoreResignDismissed = true
                        continuation.resume(returning: false)
                    }
                }
                
                self.verboseLog("[Authentication] showResignScreenIfNecessary: presenting resignViewController...")
                let presented = self.present(resignViewController)
                self.verboseLog("[Authentication] showResignScreenIfNecessary: present returned \(presented)")
                if !presented {
                    self.debugLog("[Authentication] showResignScreenIfNecessary: present failed, resuming continuation with false")
                    continuation.resume(returning: false)
                }
            }
        }
    }
}




extension ALTAppleAPI {
    func fetchAccount2(session: ALTAppleAPISession, completionHandler: @escaping (Result<ALTAccount, Error>) -> Void) {
        let url = URL(string: "viewDeveloper.action", relativeTo: self.baseURL)!
        
        self.sendRequest(with: url, additionalParameters: nil, session: session, team: nil) { (responseDictionary, requestError) in
            do {
                guard let responseDictionary = responseDictionary else { throw requestError ?? ALTAppleAPIError.unknown() }
                
                guard let account = try self.processResponse(responseDictionary, parseHandler: { () -> Any? in
                    guard let dictionary = responseDictionary["developer"] as? [String: Any] else { return nil }
                    let account = ALTAccount(responseDictionary: dictionary)
                    return account
                }, resultCodeHandler: nil) as? ALTAccount else {
                    throw ALTAppleAPIError.unknown()
                }

                completionHandler(.success(account))
            } catch {
                completionHandler(.failure(error))
            }
        }
    }

    func fetchAccount2(session: ALTAppleAPISession) async throws -> ALTAccount {
        try await withCheckedThrowingContinuation { continuation in
            self.fetchAccount2(session: session) { result in
                continuation.resume(with: result)
            }
        }
    }
}

extension ALTAppleAPI {
    func fetchCertificates(for team: ALTTeam, session: ALTAppleAPISession) async throws -> [ALTCertificate] {
        try await withCheckedThrowingContinuation { continuation in
            self.fetchCertificates(for: team, session: session) { (certs, err) in
                if let certs = certs {
                    continuation.resume(returning: certs)
                } else {
                    continuation.resume(throwing: err ?? OperationError.unknown())
                }
            }
        }
    }

    func addCertificate(machineName: String, to team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTCertificate {
        try await withCheckedThrowingContinuation { continuation in
            self.addCertificate(machineName: machineName, to: team, session: session) { (cert, err) in
                if let cert = cert {
                    continuation.resume(returning: cert)
                } else {
                    continuation.resume(throwing: err ?? OperationError.unknown())
                }
            }
        }
    }

    func revoke(_ certificate: ALTCertificate, for team: ALTTeam, session: ALTAppleAPISession) async throws {
        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
            self.revoke(certificate, for: team, session: session) { (success, err) in
                if success {
                    continuation.resume()
                } else {
                    continuation.resume(throwing: err ?? OperationError.unknown())
                }
            }
        }
    }

    func fetchDevices(for team: ALTTeam, types: ALTDeviceType, session: ALTAppleAPISession) async throws -> [ALTDevice] {
        try await withCheckedThrowingContinuation { continuation in
            self.fetchDevices(for: team, types: types, session: session) { (devices, err) in
                if let devices = devices {
                    continuation.resume(returning: devices)
                } else {
                    continuation.resume(throwing: err ?? OperationError.unknown())
                }
            }
        }
    }

    func registerDevice(name: String, identifier: String, type: ALTDeviceType, team: ALTTeam, session: ALTAppleAPISession) async throws -> ALTDevice {
        try await withCheckedThrowingContinuation { continuation in
            self.registerDevice(name: name, identifier: identifier, type: type, team: team, session: session) { (device, err) in
                if let device = device {
                    continuation.resume(returning: device)
                } else {
                    continuation.resume(throwing: err ?? OperationError.unknown())
                }
            }
        }
    }

    func fetchTeams(for account: ALTAccount, session: ALTAppleAPISession) async throws -> [ALTTeam] {
        try await withCheckedThrowingContinuation { continuation in
            self.fetchTeams(for: account, session: session) { (teams, err) in
                if let teams = teams {
                    continuation.resume(returning: teams)
                } else {
                    continuation.resume(throwing: err ?? OperationError.unknown())
                }
            }
        }
    }

    func authenticate(appleID: String, password: String, anisetteData: ALTAnisetteData, verificationHandler: ((@escaping (String?) -> Void) -> Void)?) async throws -> (ALTAccount, ALTAppleAPISession) {
        try await withCheckedThrowingContinuation { continuation in
            self.authenticate(appleID: appleID, password: password, anisetteData: anisetteData, verificationHandler: verificationHandler) { (account, session, error) in
                if let account = account, let session = session {
                    continuation.resume(returning: (account, session))
                } else {
                    continuation.resume(throwing: error ?? OperationError.unknown())
                }
            }
        }
    }
}
