name: CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: fwal/setup-swift@v2
        with:
          swift-version: '5.8'
      - name: Build
        run: swift build --disable-sandbox
      - name: Run Tests
        run: swift test --disable-sandbox
